# permissions for end users to view cacheservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kcp-operator
    app.kubernetes.io/managed-by: kustomize
  name: cacheserver-viewer-role
rules:
- apiGroups:
  - operator.kcp.io
  resources:
  - cacheservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.kcp.io
  resources:
  - cacheservers/status
  verbs:
  - get
