# permissions for end users to edit frontproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kcp-operator
    app.kubernetes.io/managed-by: kustomize
  name: frontproxy-editor-role
rules:
- apiGroups:
  - operator.kcp.io
  resources:
  - frontproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.kcp.io
  resources:
  - frontproxies/status
  verbs:
  - get
