# permissions for end users to view kubeconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kcp-operator
    app.kubernetes.io/managed-by: kustomize
  name: kubeconfig-viewer-role
rules:
- apiGroups:
  - operator.kcp.io
  resources:
  - kubeconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.kcp.io
  resources:
  - kubeconfigs/status
  verbs:
  - get
