# permissions for end users to view shards.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kcp-operator
    app.kubernetes.io/managed-by: kustomize
  name: shard-viewer-role
rules:
- apiGroups:
  - operator.kcp.io
  resources:
  - shards
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.kcp.io
  resources:
  - shards/status
  verbs:
  - get
